---
### MODEL ###
model_path: "./models/face_landmarker_v2_with_blendshapes.task"

### ALGORITHM ###
num_faces: 1
min_face_detection_confidence: 0.4
min_face_presence_confidence: 0.6
blink_threshold_pitch: 0.7
blink_threshold_wo_pitch: 0.4

### CAMERA ###
camera_id: 0
frame_width: 1280
frame_height: 720
frame_rate: 15

### RPI ###
led_pin: 17
